server:
  port: 8080
spring:
  application:
    name: inventory
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    producer:
      retries: 5
      acks: all
      properties:
        enable:
          idempotence: true   # Set Producer exactly once Trx
    consumer:
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed         
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          transaction:
            transactionIdPrefix: tx-${random.uuid}   
        bindings:
          event-in:
            consumer:
              autoCommitOffset: false    # Disable Offset auto commit
              enableDlq: true
              dlqName: dlq-labshoppubsub
              dlqPartitions: 1         
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: inventory
          destination: labshoppubsub
          contentType: application/json
        event-out:
          destination: labshoppubsub
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8082

---

spring:
  profiles: docker
  kafka:
    producer:
      retries: 5
      acks: all
      properties:
        enable:
          idempotence: true   # Set Producer exactly once Trx
    consumer:
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed    
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
          transaction:
            transactionIdPrefix: tx-${random.uuid}   
        bindings:
          event-in:
            consumer:
              autoCommitOffset: false    # Disable Offset auto commit
              enableDlq: true
              dlqName: dlq-labshoppubsub
              dlqPartitions: 1              
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: inventory
          destination: labshoppubsub
          contentType: application/json
        event-out:
          destination: labshoppubsub
          contentType: application/json


